# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7s25csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ddr_test/ddr_test/ddr_test.cache/wt [current_project]
set_property parent.project_path C:/ddr_test/ddr_test/ddr_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Xilinx_Proj/vivado-boards-master/new/board_files} [current_project]
set_property board_part digilentinc.com:arty-s7-25:part0:1.0 [current_project]
set_property ip_repo_paths c:/Xilinx_Proj/IP [current_project]
update_ip_catalog
set_property ip_output_repo c:/ddr_test/ddr_test/ddr_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/example_top.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_afifo.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_cmd_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_cmd_prbs_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_data_prbs_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_init_mem_pattern_ctr.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_memc_flow_vcontrol.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_memc_traffic_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_rd_data_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_read_data_path.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_read_posted_fifo.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_s7ven_data_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_tg_prbs_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_tg_status.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_traffic_gen_top.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_vio_init_pattern_bram.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_wr_data_gen.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/example_design/rtl/traffic_gen/mig_7series_v4_2_write_data_path.v
  C:/ddr_test/ddr_test/ddr_test.srcs/sources_1/new/imp_top.v
}
read_ip -quiet c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/ddr_test/ddr_test/ddr_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/ddr_test/ddr_test/ddr_test.srcs/constrs_1/Arty-S7-25-Master.xdc
set_property used_in_implementation false [get_files C:/ddr_test/ddr_test/ddr_test.srcs/constrs_1/Arty-S7-25-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top imp_top -part xc7s25csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef imp_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file imp_top_utilization_synth.rpt -pb imp_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
